### ISSUE TITLE
Neither --daemon nor --tryDeaemon work on macOS

### ISSUE THREAD

**Issue by tssm** [yatli/fvim#100]
In the first case the app crashes with the following message:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for '<StartupCode$FVim>.$FVim.Shell' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/Applications/FVim.app/Contents/MacOS/icons'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 enumerable)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at <StartupCode$FVim>.$FVim.Shell..cctor()
   --- End of inner exception stack trace ---
   at FVim.Shell.daemon(FSharpOption`1 port, FSharpOption`1 pipe, Options _arg1)
   at FVim.Program.Main(String[] args)
```

There's no `/Applications/FVim.app/Contents/MacOS/icons` on my system at all.

Per [README.md](https://github.com/yatli/fvim#startup-options) I expected `--tryDaemon` to launch FVim with an embedded Neovim instance because there's no daemon running, instead I got:

<img width="1150" alt="Screenshot 2019-11-24 at 13 08 11" src="https://user-images.githubusercontent.com/1188977/69494393-7bfbe380-0ebb-11ea-8b88-6983ac5c1ff4.png">

**Comment by yatli** [comment]
Should be fixed now.
