### ISSUE TITLE
--termcmd option not recognized

### ISSUE THREAD

**Issue by rashil2000** [yatli/fvim#180]
I ran the command `fvim --termcmd powershell`, here's the stacktrace:

<details>
  <summary>Exit code: 1<br>
Exception message: neovim crashed<br>
nvim.exe: Unknown option argument: "--termcmd" More info with "nvim.exe -h" 
  </summary>

   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at FVim.states.msg_dispatch(Event _arg1) in D:\a\1\s\states.fs:line 285
   at FVim.model.Start@146.Invoke(Event _arg1) in D:\a\1\s\model.fs:line 146
   at FSharp.Control.Reactive.ObservableModule.subscribe@1674-2.Invoke(T delegateArg0)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 44
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 50
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 118
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass8_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at FVim.Program.app@126-1.Invoke(Window win) in D:\a\1\s\Program.fs:line 129
   at FVim.Program.startMainWindow(FSharpFunc`2 app, ServerOptions serveropts_0, Boolean serveropts_1, Boolean serveropts_2) in D:\a\1\s\Program.fs:line 78
   at FVim.Program.Main(String[] args) in D:\a\1\s\Program.fs:line 138

</details>

**Comment by yatli** [comment]
What is the expected behavior?

**Comment by rashil2000** [comment]
According to the Readme
![image](https://user-images.githubusercontent.com/46838874/125780050-30bf25a1-d401-4498-9282-05abd4011876.png)
it should launch a terminal with powershell (by default it launches with cmd)

**Comment by yatli** [comment]
Aha. Totally forgot about this :D
The arg is actually `--terminal-cmd`.
I'll update the README, thanks!

**Comment by rashil2000** [comment]
Unfortunately, it still doesn't work. I've tried
```
fvim --terminal-cmd pwsh
fvim --terminal --terminal-cmd pwsh
fvim --terminal-cmd pwsh --terminal
```

All of these just open a blank buffer.

**Comment by yatli** [comment]
Could you try this:
`fvim -u NORC +"set mouse=a" +"set noshowmode" +"set laststatus=0" +"set noruler" +"set noshowcmd" +terminal pwsh`

**Comment by rashil2000** [comment]
It opens up cmd in FVim

**Comment by yatli** [comment]
@rashil2000 updated the line, pls try again

**Comment by yatli** [comment]
I'm guessing it's some quote escape problem again so that fvim fail to assemble the correct startup args

**Comment by rashil2000** [comment]
Yes, now the line works

**Comment by yatli** [comment]
thanks for confirming. I'll figure out a fix.
