### ISSUE TITLE
Remote connection to localhost not working

### ISSUE THREAD

**Issue by rashil2000** [yatli/fvim#181]
I run `nvim --headless --listen localhost:6666` in one terminal, and `fvim --nvr localhost:6666` in another. But this gives me an error:
<details><summary>Exit code: 0<br>
Exception message: No connection could be made because the target machine actively refused it. 127.0.0.1:6666</summary>
  at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at FVim.neovim.Nvim.createIO(ServerOptions serveropts) in D:\a\1\s\neovim.fs:line 65
   at FVim.neovim.Nvim.start(ServerOptions opts) in D:\a\1\s\neovim.fs:line 101
   at FVim.model.Start(ServerOptions serveropts, Boolean norc, Boolean debugMultigrid) in D:\a\1\s\model.fs:line 144
   at FVim.Program.startMainWindow(FSharpFunc`2 app, ServerOptions serveropts_0, Boolean serveropts_1, Boolean serveropts_2) in D:\a\1\s\Program.fs:line 59
   at FVim.Program.Main(String[] args) in D:\a\1\s\Program.fs:line 138
</details>

I have tried doing `pip install neovim-remote` too, but it doesn't help.

[OS: Windows 10]

**Comment by rashil2000** [comment]
This is really strange, but changing the first command to `nvim --headless --listen 127.0.01:6666` works fine.
