### ISSUE TITLE
windows10 fvim crash (version: v0.3.412+g3b521db, fvim-win-x64, in win10)

### ISSUE THREAD

**Issue by menghuu** [yatli/fvim#198]
the stack trace infomations are:

```
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at FVim.neovim.Nvim.createIO(ServerOptions serveropts)
   at FVim.neovim.Nvim.start(ServerOptions opts)
   at FVim.model.Start(ServerOptions serveropts, Boolean norc, Boolean debugMultigrid)
   at FVim.Program.startMainWindow(FSharpFunc`2 app, ServerOptions serveropts_0, Boolean serveropts_1, Boolean serveropts_2)
   at FVim.Program.Main(String[] args)
```

**Comment by yatli** [comment]
check your neovim installation it's not in your path.
