### ISSUE TITLE
linux port broken

### ISSUE THREAD

**Issue by yatli** [yatli/fvim#20]

**Comment by yatli** [comment]
root cause identified:

```
editor #1: drawBuffer: System.DllNotFoundException: Unable to load shared library 'libHarfBuzzSharp' or one of its dependencies. In
 order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibHarfBuzzSharp: cannot open shar
ed object file: No such file or directory
   at HarfBuzzSharp.HarfBuzzApi.hb_blob_create(IntPtr data, UInt32 length, MemoryMode mode, IntPtr user_data, IntPtr destroy)
   at HarfBuzzSharp.Blob.Create(IntPtr data, UInt32 length, MemoryMode mode, Object user_data, BlobReleaseDelegate releaseProc)
   at HarfBuzzSharp.Blob..ctor(IntPtr data, UInt32 length, MemoryMode mode, Object userData, BlobReleaseDelegate releaseDelegate)
   at SkiaSharp.HarfBuzz.BlobExtensions.ToHarfBuzzBlob(SKStreamAsset asset)
   at SkiaSharp.HarfBuzz.SKShaper..ctor(SKTypeface typeface)
   at FVim.ui.RenderText(IDrawingContextImpl ctx, Rect region, SKPaint fg, SKPaint bg, SKPaint sp, Boolean underline, Boolean under
curl, String text, Boolean useShaping) in /home/yatao/git/fvim/ui.fs:line 238
   at FVim.Editor.drawBuffer(IDrawingContextImpl ctx, Int32 row, Int32 col, Int32 colend, Int32 hlid, FSharpList`1 str, Boolean iss
ym) in /home/yatao/git/fvim/Views/Editor.xaml.fs:line 111
```

**Comment by yatli** [comment]
fixed by adding the linux native assets for harfbuzzsharp
