### ISSUE TITLE
Crash when using Git bash in terminal

### ISSUE THREAD

**Issue by JulesNP** [yatli/fvim#201]
I'm regularly getting crashes of FVim when running bash in the FVim terminal on Windows 10. My default terminal is cmd.exe, and I'm running Git's bash.exe from within cmd.
The crash seems to occur whenever I run a command that produces an error message, e.g. a failed npm build. I've tested the same process directly though neovim, but it doesn't produce an crash there.

```
Exit code: -1073741819
Exception message: neovim crashed

Stack trace:
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in D:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
   at FVim.model.rpc.msg_dispatch(Event _arg1) in D:\a\1\s\model.fs:line 219
   at FVim.model.Start@312.Invoke(Event _arg1) in D:\a\1\s\model.fs:line 312
   at FSharp.Control.Reactive.ObservableModule.subscribe@1681-2.Invoke(T delegateArg0)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Concurrency.ObserveOn`1.Context._.OnNextPosted(Object value) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Synchronization.ObserveOn.cs:line 118
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 157
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 62
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 117
   at FVim.Program.app@152-1.Invoke(Window win) in D:\a\1\s\Program.fs:line 155
   at FVim.Program.startMainWindow(FSharpFunc`2 app, ServerOptions serveropts_0, Boolean serveropts_1) in D:\a\1\s\Program.fs:line 102
   at FVim.Program.Main(String[] args) in D:\a\1\s\Program.fs:line 164
```

**Comment by yatli** [comment]
Do you use mouse scroll to view the failure messages?
See: https://github.com/neovim/neovim/issues/15075

**Comment by JulesNP** [comment]
Yes, upon testing again, that seems to be the cause. I'm unable to reproduce the crash if I use "set mouse-=a" first.

**Comment by yatli** [comment]
Thanks for confirming. You can use the neovim HEAD/nightly, or wait for the next release.
