### ISSUE TITLE
MacOS Fvim exited unexpectedly!

### ISSUE THREAD

**Issue by anyway-blows** [yatli/fvim#214]
I did have a neovim installed on my mac. And I have added the directory of neovim into PATH.
PATH:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/63783368/155051363-216a0aff-5d50-43a9-ae2e-25b08ee21039.png">

Screen shot:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/63783368/155051212-13269877-5a9f-4b58-ac99-de6a27789098.png">

```
Exit code: 0
Exception message: No such file or directory
```

Stack Trace:
```
at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at FVim.neovim.Nvim.createIO(ServerOptions serveropts) in /Users/runner/work/1/s/neovim.fs:line 63
   at FVim.neovim.Nvim.start(ServerOptions opts) in /Users/runner/work/1/s/neovim.fs:line 104
   at FVim.model.Start(ServerOptions serveropts, Boolean norc, Boolean remote) in /Users/runner/work/1/s/model.fs:line 345
   at FVim.Program.startMainWindow(FSharpFunc`2 app, ServerOptions opts_0, Boolean opts_1, Boolean opts_2) in /Users/runner/work/1/s/Program.fs:line 34
   at FVim.Program.Main(String[] args) in /Users/runner/work/1/s/Program.fs:line 130
```

**Comment by yatli** [comment]
How did you add the PATH? Ad-hoc export won't work and you'll need to do it with rc file.

**Comment by yatli** [comment]
@anyway-blows how about the latest release? A new launcher script is included.

**Comment by nikbrunner** [comment]
I am having the same problem, regardless if install it via the Releases Download or Homebrew

macOS Monterey (12.22)
Apple M1 Max

![image](https://user-images.githubusercontent.com/46924729/176735861-27a5fb96-73b9-4c68-803d-e64b8239db55.png)
