### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Neftedollar** [yatli/fvim#23]
Hey!
Where can I find instructions?
How can I run it?
What should I install?
Etc.

**Comment by yatli** [comment]
See: https://github.com/yatli/fvim/releases

**Comment by yatli** [comment]
It's pretty self-contained so you'll just need to download a package suitable for your system.
After it's downloaded, just extract the content and run `FVim`.

**Comment by yatli** [comment]
@Neftedollar updated README.md to reflect this. Thanks!

**Comment by Neftedollar** [comment]
Thank you!

**Comment by Neftedollar** [comment]
hey! I've tried it.
Mac OS 10.14.5
```sh
fvim-osx-x64 dotnet FVim.dll

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at FVim.neovim.rpc.Process.start(Options _arg1) in C:\projects\fvim\neovim\neovim.rpc.fs:line 279
   at FVim.Model.Start(Options opts) in C:\projects\fvim\neovim\neovim.model.fs:line 328
   at FVim.Program.AppMain(Application app, String[] args) in C:\projects\fvim\Program.fs:line 36
   at FVim.Program.Main@51.Invoke(Application delegateArg0, String[] delegateArg1) in C:\projects\fvim\Program.fs:line 51
   at Avalonia.Controls.AppBuilderBase`1.Start(AppMainDelegate main, String[] args)
   at FVim.Program.Main(String[] args) in C:\projects\fvim\Program.fs:line 52
[1]    3920 abort      dotnet FVim.dll
```

Should I install nvim before it?

Sorry I'm so newbie

**Comment by Neftedollar** [comment]
@yatli

**Comment by yatli** [comment]
do you have `nvim` in your `$PATH`?

**Comment by yatli** [comment]
also, there should be a `FVim` executable in the package -- maybe you'll need to `chmod +x` that one.
It's self-contained so you don't have to install `dotnet`;
I'm also using the latest `netcoreapp3.0 preview 6` so if you run it with an older dotnet installation it might not run.

**Comment by yatli** [comment]
@Neftedollar knock knock, after-sale feedback :)

**Comment by Neftedollar** [comment]
@yatli, sorry, didn't try it yet.

**Comment by yatli** [comment]
no worries, just ping back when you feel like giving it another try :)

**Comment by yatli** [comment]
Closing due to inactivity.

**Comment by Neftedollar** [comment]
finaly! I've tryed it!
It's good

**Comment by Neftedollar** [comment]
@yatli  it's mach better when it's `.app` file
On Monday I'll try to use it with windows.
Thank you again!
