### ISSUE TITLE
random crashes

### ISSUE THREAD

**Issue by yatli** [yatli/fvim#24]
Started in recent days.
Made a basic crash reporter and let's see if I can get the fish by luck.

**Comment by yatli** [comment]
observation: when fvim becomes unresponsive (and then killed), the nvim process locks up and spins on a core.

**Comment by yatli** [comment]
possible root cause:
```
Unhandled exception: (terminating:true)
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at FVim.ui.GridRegion.Regions() in C:\Users\yatli\git\fvim\ui.fs:line 150
   at FVim.Editor.Render(DrawingContext ctx) in C:\Users\yatli\git\fvim\Views\Editor.xaml.fs:line 235
   at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, IVisual visual, Rect clipRect)
   at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, IVisual visual, Rect clipRect)
   at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, IVisual visual, Rect clipRect)
   at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, IVisual visual, Rect clipRect)
   at Avalonia.Rendering.ImmediateRenderer.Render(DrawingContext context, IVisual visual, Rect clipRect)
   at Avalonia.Rendering.ImmediateRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)

```

**Comment by yatli** [comment]
there seems to be another case, that `nvim` itself exits.

**Comment by yatli** [comment]
looks like this is fixed.
