### ISSUE TITLE
Exception message: An error occurred trying to start process 'nvim' with working directory '/'. No such file or directory 

### ISSUE THREAD

**Issue by danny-su** [yatli/fvim#275]
```
Exit code: 0
Exception message: An error occurred trying to start process 'nvim' with working directory '/'. No such file or directory 
```

```
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo , String , String[] , String[] , String , Boolean , UInt32 , UInt32 , UInt32[] , Int32& , Int32& , Int32& , Boolean , Boolean )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo )
   at System.Diagnostics.Process.Start()
   at FVim.neovim.Nvim.createIO(ServerOptions serveropts) in /Users/runner/work/1/s/neovim.fs:line 62
   at FVim.neovim.Nvim.start(ServerOptions opts) in /Users/runner/work/1/s/neovim.fs:line 103
   at FVim.model.Start(ServerOptions serveropts, Boolean norc, Boolean remote) in /Users/runner/work/1/s/model.fs:line 344
   at FVim.Program.startMainWindow(FSharpFunc`2 app, ServerOptions opts_0, Boolean opts_1, Boolean opts_2) in /Users/runner/work/1/s/Program.fs:line 34
   at FVim.Program.Main(String[] args) in /Users/runner/work/1/s/Program.fs:line 141
```
<img width="1296" alt="image" src="https://github.com/user-attachments/assets/7d063c9f-fe1d-4ae6-a45c-b60e29f3299f">

<img width="304" alt="image" src="https://github.com/user-attachments/assets/8b193839-82ef-404e-b3bb-f41d9df67c69">

**Comment by gtubolcev** [comment]
I've got a similar error on Linux (ubuntu 24.04).

<img width="1920" height="998" alt="Image" src="https://github.com/user-attachments/assets/68483299-1f0f-4132-91bc-958b4908f272" />
