### ISSUE TITLE
Fvim crashes at startup

### ISSUE THREAD

**Issue by LiteracyFanatic** [yatli/fvim#89]
I get the following output when I build and run following the directions in the README.md. Tested on Arch Linux 5.3.8.

```
log: fvim started. time = 11/2/2019 8:40:32 AM
model: starting neovim instance...
model: opts = { intent = Start
  logToStdout = false
  logToFile = false
  logPatterns = None
  args = ["--embed"; "-C"; "release"]
  program = "nvim"
  stderrenc = System.Text.UTF8Encoding+UTF8EncodingSealed
  serveropts = StartNew }
neovim.process: Starting process. Program: nvim; Arguments: --embed -C release
neovim.process: begin read loop
model: commencing early initialization...
neovim.process: exception: System.InvalidOperationException: Invalid MessagePack code was detected, code:-1
   at MessagePack.MessagePackBinary.ReadMessageBlockFromStreamCore(Stream stream, Byte[]& bytes, Int32 offset, Boolean readOnlySingleMessage)
   at MessagePack.MessagePackBinary.ReadMessageBlockFromStreamUnsafe(Stream stream, Boolean readOnlySingleMessage, Int32& readSize)
   at MessagePack.MessagePackSerializer.Deserialize[T](Stream stream, IFormatterResolver resolver, Boolean readStrict)
   at MessagePack.MessagePackSerializer.Deserialize[T](Stream stream, Boolean readStrict)
   at FVim.neovim.read@112-1.Invoke() in /home/jordan/src/fvim/neovim.fs:line 117
neovim.process: end read loop: process exited, code = 1
neovim.process: call: 0 -> [0,0,"nvim_get_api_info",[]]
model: neovim crashed with code 1
```

**Comment by yatli** [comment]
what's your nvim version?

**Comment by LiteracyFanatic** [comment]
```
$ nvim --version

NVIM v0.4.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.2/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by yatli** [comment]
In your log:

```
  args = ["--embed"; "-C"; "release"]
```

are you running it with `-C release`? This looks like a `dotnet run` option, not something neovim takes.

**Comment by yatli** [comment]
also, the `dotnet` option should be lowercase -c with uppercase Release: `-c Release`

**Comment by yatli** [comment]
if you want to start with `dotnet run`:

`dotnet run -c Release -- foo.txt`

**Comment by LiteracyFanatic** [comment]
Oops, my bad. I capitalized the `-c` by mistake.
